site_name: haca
nav:
    - Demo: demo.md
    - Install: install.md
    - cli: cli.md
    - REST API: rest-api.md

theme: material
repo_url: https://github.com/henrik-andreasson/haca
repo_name: haca
copyright: "&copy 2022 Henrik Andreasson"
markdown_extensions:
    - admonition
    - smarty
    - abbr
    - attr_list
    - fenced_code
    - footnotes
    - tables
    - codehilite
    - meta
    - toc:
        title: title
        permalink: True
    - sane_lists
