"""revokaction_time

Revision ID: 09b07a49176f
Revises: e1e457d5c24d
Create Date: 2022-05-26 19:42:38.829111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b07a49176f'
down_revision = 'e1e457d5c24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revocation_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('revocation_time')

    # ### end Alembic commands ###
