"""certserial

Revision ID: e1e457d5c24d
Revises: e6789bd50de9
Create Date: 2022-05-26 18:52:14.825281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e457d5c24d'
down_revision = 'e6789bd50de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certserialnumber', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('certserialnumber')

    # ### end Alembic commands ###
